import {
  User,
  MessageSquare,
  Radio,
  Users,
  Lock,
  Trash2,
  Repeat,
  Heart,
  Award,
  MessageCircle,
  Eye,
  EyeOff,
  Image,
  Video,
  Hash,
  FileText,
  AlertCircle,
  ShoppingBag,
  Zap,
  Pin,
  Bookmark,
  Settings,
  List,
  Smile,
  FileCode,
  GitBranch,
  Flag,
  Tag,
  Calendar,
  Wallet,
  Package,
  Map,
  Highlighter,
  BarChart3,
  Timer,
  ListChecks,
  Mic,
  Key,
  Cloud,
  UserCheck,
  UserX,
  Shield,
  type LucideIcon,
} from "lucide-react";

export interface EventKind {
  kind: number | string;
  name: string;
  description: string;
  nip: string;
  icon: LucideIcon;
}

export const EVENT_KINDS: Record<number | string, EventKind> = {
  // Core protocol kinds
  0: {
    kind: 0,
    name: "Profile",
    description: "User Metadata",
    nip: "01",
    icon: User,
  },
  1: {
    kind: 1,
    name: "Note",
    description: "Short Text Note",
    nip: "10",
    icon: MessageSquare,
  },
  2: {
    kind: 2,
    name: "Relay Recommendation",
    description: "Recommend Relay",
    nip: "01",
    icon: Radio,
  },
  3: {
    kind: 3,
    name: "Contacts",
    description: "Follows",
    nip: "02",
    icon: Users,
  },
  4: {
    kind: 4,
    name: "Encrypted DM",
    description: "Encrypted Direct Messages",
    nip: "04",
    icon: Lock,
  },
  5: {
    kind: 5,
    name: "Deletion",
    description: "Event Deletion Request",
    nip: "09",
    icon: Trash2,
  },
  6: {
    kind: 6,
    name: "Repost",
    description: "Repost",
    nip: "18",
    icon: Repeat,
  },
  7: {
    kind: 7,
    name: "Reaction",
    description: "Reaction",
    nip: "25",
    icon: Heart,
  },
  8: {
    kind: 8,
    name: "Badge Award",
    description: "Badge Award",
    nip: "58",
    icon: Award,
  },
  9: {
    kind: 9,
    name: "Chat",
    description: "Chat Message",
    nip: "C7",
    icon: MessageCircle,
  },

  // Group chat
  10: {
    kind: 10,
    name: "Group Reply",
    description: "Group Chat Threaded Reply",
    nip: "29",
    icon: MessageCircle,
  },
  11: {
    kind: 11,
    name: "Thread",
    description: "Thread",
    nip: "7D",
    icon: MessageSquare,
  },
  12: {
    kind: 12,
    name: "Group Thread",
    description: "Group Thread Reply",
    nip: "29",
    icon: MessageCircle,
  },
  13: { kind: 13, name: "Seal", description: "Seal", nip: "59", icon: Lock },
  14: {
    kind: 14,
    name: "Direct Message",
    description: "Direct Message",
    nip: "17",
    icon: MessageSquare,
  },
  15: {
    kind: 15,
    name: "File Message",
    description: "File Message",
    nip: "17",
    icon: FileText,
  },
  16: {
    kind: 16,
    name: "Generic Repost",
    description: "Generic Repost",
    nip: "18",
    icon: Repeat,
  },
  17: {
    kind: 17,
    name: "Website Reaction",
    description: "Reaction to a website",
    nip: "25",
    icon: Heart,
  },

  18: {
    kind: 18,
    name: "Repost",
    description: "Repost with optional comment",
    nip: "18",
    icon: Repeat,
  },

  // Media
  20: {
    kind: 20,
    name: "Picture",
    description: "Picture",
    nip: "68",
    icon: Image,
  },
  21: {
    kind: 21,
    name: "Video",
    description: "Video Event",
    nip: "71",
    icon: Video,
  },
  22: {
    kind: 22,
    name: "Short Video",
    description: "Short-form Portrait Video Event",
    nip: "71",
    icon: Video,
  },

  // Channels
  40: {
    kind: 40,
    name: "Channel Create",
    description: "Channel Creation",
    nip: "28",
    icon: Hash,
  },
  41: {
    kind: 41,
    name: "Channel Metadata",
    description: "Channel Metadata",
    nip: "28",
    icon: Settings,
  },
  42: {
    kind: 42,
    name: "Channel Message",
    description: "Channel Message",
    nip: "28",
    icon: MessageSquare,
  },
  43: {
    kind: 43,
    name: "Channel Hide",
    description: "Channel Hide Message",
    nip: "28",
    icon: EyeOff,
  },
  44: {
    kind: 44,
    name: "Channel Mute",
    description: "Channel Mute User",
    nip: "28",
    icon: Eye,
  },

  // Special events
  62: {
    kind: 62,
    name: "Vanish Request",
    description: "Request to Vanish",
    nip: "62",
    icon: Trash2,
  },
  64: {
    kind: 64,
    name: "Chess",
    description: "Chess (PGN)",
    nip: "64",
    icon: Package,
  },

  // Data vending machine
  5000: {
    kind: 5000,
    name: "Job Request",
    description: "Data vending machine job request",
    nip: "90",
    icon: BarChart3,
  },
  6000: {
    kind: 6000,
    name: "Job Result",
    description: "Data vending machine job result",
    nip: "90",
    icon: BarChart3,
  },
  7000: {
    kind: 7000,
    name: "Job Feedback",
    description: "Job feedback",
    nip: "90",
    icon: MessageCircle,
  },

  // Marketplace
  1021: {
    kind: 1021,
    name: "Bid",
    description: "Bid",
    nip: "15",
    icon: ShoppingBag,
  },
  1022: {
    kind: 1022,
    name: "Bid Confirm",
    description: "Bid confirmation",
    nip: "15",
    icon: ShoppingBag,
  },

  // Content
  1040: {
    kind: 1040,
    name: "Timestamp",
    description: "OpenTimestamps",
    nip: "03",
    icon: Calendar,
  },
  1059: {
    kind: 1059,
    name: "Gift Wrap",
    description: "Gift Wrap",
    nip: "59",
    icon: Package,
  },
  1063: {
    kind: 1063,
    name: "File Metadata",
    description: "File Metadata",
    nip: "94",
    icon: FileText,
  },
  1068: {
    kind: 1068,
    name: "Poll",
    description: "Poll",
    nip: "88",
    icon: ListChecks,
  },
  1018: {
    kind: 1018,
    name: "Poll Response",
    description: "Response to a poll",
    nip: "88",
    icon: ListChecks,
  },
  1111: {
    kind: 1111,
    name: "Comment",
    description: "Comment",
    nip: "22",
    icon: MessageCircle,
  },
  1244: {
    kind: 1244,
    name: "Voice Comment",
    description: "Voice Message Comment",
    nip: "A0",
    icon: Mic,
  },
  1222: {
    kind: 1222,
    name: "Voice Message",
    description: "Voice Message",
    nip: "A0",
    icon: MessageCircle,
  },
  1311: {
    kind: 1311,
    name: "Live Chat",
    description: "Live Chat Message",
    nip: "53",
    icon: MessageCircle,
  },
  1337: {
    kind: 1337,
    name: "Code",
    description: "Code Snippet",
    nip: "C0",
    icon: FileCode,
  },

  // Git stuff
  1617: {
    kind: 1617,
    name: "Patches",
    description: "Git Patches",
    nip: "34",
    icon: GitBranch,
  },
  1618: {
    kind: 1618,
    name: "Pull Request",
    description: "Git Pull Requests",
    nip: "34",
    icon: GitBranch,
  },
  1619: {
    kind: 1619,
    name: "Git Status",
    description: "Git repository status",
    nip: "34",
    icon: GitBranch,
  },
  1621: {
    kind: 1621,
    name: "Issue",
    description: "Git Issues",
    nip: "34",
    icon: AlertCircle,
  },
  1622: {
    kind: 1622,
    name: "Release",
    description: "Git Release Artifacts",
    nip: "34",
    icon: Package,
  },
  818: {
    kind: 818,
    name: "Merge Request",
    description: "Merge Requests",
    nip: "54",
    icon: GitBranch,
  },

  // Moderation
  1984: {
    kind: 1984,
    name: "Report",
    description: "Reporting",
    nip: "56",
    icon: Flag,
  },
  1985: {
    kind: 1985,
    name: "Label",
    description: "Label",
    nip: "32",
    icon: Tag,
  },

  // Community
  4550: {
    kind: 4550,
    name: "Community Post",
    description: "Community Post Approval",
    nip: "72",
    icon: Users,
  },

  // Torrents
  2003: {
    kind: 2003,
    name: "Torrent",
    description: "Torrent",
    nip: "35",
    icon: Package,
  },
  2004: {
    kind: 2004,
    name: "Torrent Comment",
    description: "Torrent Comment",
    nip: "35",
    icon: MessageCircle,
  },

  // Zaps
  9041: {
    kind: 9041,
    name: "Zap Goal",
    description: "Zap Goal",
    nip: "75",
    icon: Zap,
  },
  9734: {
    kind: 9734,
    name: "Zap Request",
    description: "Zap Request",
    nip: "57",
    icon: Zap,
  },
  9735: { kind: 9735, name: "Zap", description: "Zap", nip: "57", icon: Zap },
  9802: {
    kind: 9802,
    name: "Highlight",
    description: "Highlights",
    nip: "84",
    icon: Highlighter,
  },

  // Lists (kind 10000+)
  10000: {
    kind: 10000,
    name: "Mute List",
    description: "Mute list",
    nip: "51",
    icon: EyeOff,
  },
  10001: {
    kind: 10001,
    name: "Pin List",
    description: "Pin list",
    nip: "51",
    icon: Pin,
  },
  10002: {
    kind: 10002,
    name: "Relay List",
    description: "Relay List Metadata",
    nip: "65",
    icon: Radio,
  },
  10003: {
    kind: 10003,
    name: "Bookmarks",
    description: "Bookmark list",
    nip: "51",
    icon: Bookmark,
  },
  10004: {
    kind: 10004,
    name: "Communities",
    description: "Communities list",
    nip: "51",
    icon: Users,
  },
  10005: {
    kind: 10005,
    name: "Public Chats",
    description: "Public chats list",
    nip: "51",
    icon: MessageCircle,
  },
  10006: {
    kind: 10006,
    name: "Blocked Relays",
    description: "Blocked relays list",
    nip: "51",
    icon: Radio,
  },
  10007: {
    kind: 10007,
    name: "Search Relays",
    description: "Search relays list",
    nip: "51",
    icon: Radio,
  },
  10009: {
    kind: 10009,
    name: "User Groups",
    description: "User groups list",
    nip: "51",
    icon: Users,
  },
  10015: {
    kind: 10015,
    name: "Interests",
    description: "Interests list",
    nip: "51",
    icon: Heart,
  },
  10030: {
    kind: 10030,
    name: "Emoji List",
    description: "User emoji list",
    nip: "51",
    icon: Smile,
  },
  10096: {
    kind: 10096,
    name: "File Storage",
    description: "File storage server list",
    nip: "96",
    icon: Cloud,
  },

  // Cashu
  7374: {
    kind: 7374,
    name: "Cashu Token",
    description: "Cashu Wallet Tokens",
    nip: "60",
    icon: Wallet,
  },
  7375: {
    kind: 7375,
    name: "Cashu Quote",
    description: "Cashu Mint Quote",
    nip: "60",
    icon: Wallet,
  },
  7376: {
    kind: 7376,
    name: "Cashu Request",
    description: "Cashu Melt Quote",
    nip: "60",
    icon: Wallet,
  },

  // Group Control
  9000: {
    kind: 9000,
    name: "Group Admin",
    description: "Group Control - Add User",
    nip: "29",
    icon: UserCheck,
  },
  9001: {
    kind: 9001,
    name: "Group Remove",
    description: "Group Control - Remove User",
    nip: "29",
    icon: UserX,
  },
  9002: {
    kind: 9002,
    name: "Group Edit",
    description: "Group Control - Edit Metadata",
    nip: "29",
    icon: Settings,
  },
  9003: {
    kind: 9003,
    name: "Group Add Permission",
    description: "Group Control - Add Permission",
    nip: "29",
    icon: Shield,
  },
  9004: {
    kind: 9004,
    name: "Group Remove Permission",
    description: "Group Control - Remove Permission",
    nip: "29",
    icon: Shield,
  },
  9005: {
    kind: 9005,
    name: "Group Delete",
    description: "Group Control - Delete Event",
    nip: "29",
    icon: Trash2,
  },
  9006: {
    kind: 9006,
    name: "Group Create Invite",
    description: "Group Control - Create Invite",
    nip: "29",
    icon: Users,
  },
  9007: {
    kind: 9007,
    name: "Group Join Request",
    description: "Group Control - Join Request",
    nip: "29",
    icon: Users,
  },
  9021: {
    kind: 9021,
    name: "Group Metadata",
    description: "Group Metadata",
    nip: "29",
    icon: Settings,
  },

  // Wallet & Auth
  13194: {
    kind: 13194,
    name: "Wallet Info",
    description: "Wallet Info",
    nip: "47",
    icon: Wallet,
  },
  22242: {
    kind: 22242,
    name: "Client Auth",
    description: "Client Authentication",
    nip: "42",
    icon: Key,
  },
  23194: {
    kind: 23194,
    name: "Wallet Request",
    description: "Wallet Request",
    nip: "47",
    icon: Wallet,
  },
  23195: {
    kind: 23195,
    name: "Wallet Response",
    description: "Wallet Response",
    nip: "47",
    icon: Wallet,
  },
  24133: {
    kind: 24133,
    name: "Nostr Connect",
    description: "Nostr Connect",
    nip: "46",
    icon: Key,
  },
  27235: {
    kind: 27235,
    name: "HTTP Auth",
    description: "HTTP Authentication",
    nip: "98",
    icon: Key,
  },

  // Replaceable events (kind 30000+)
  30000: {
    kind: 30000,
    name: "Follow Sets",
    description: "Follow sets",
    nip: "51",
    icon: Users,
  },
  30001: {
    kind: 30001,
    name: "Generic Lists",
    description: "Generic lists",
    nip: "51",
    icon: List,
  },
  30002: {
    kind: 30002,
    name: "Relay Sets",
    description: "Relay sets",
    nip: "51",
    icon: Radio,
  },
  30003: {
    kind: 30003,
    name: "Bookmark Sets",
    description: "Bookmark sets",
    nip: "51",
    icon: Bookmark,
  },
  30008: {
    kind: 30008,
    name: "Profile Badges",
    description: "Profile Badges",
    nip: "58",
    icon: Award,
  },
  30009: {
    kind: 30009,
    name: "Badge Definition",
    description: "Badge Definition",
    nip: "58",
    icon: Award,
  },
  30017: {
    kind: 30017,
    name: "Stall",
    description: "Create or update a stall",
    nip: "15",
    icon: ShoppingBag,
  },
  30018: {
    kind: 30018,
    name: "Product",
    description: "Create or update a product",
    nip: "15",
    icon: ShoppingBag,
  },
  30023: {
    kind: 30023,
    name: "Article",
    description: "Long-form Content",
    nip: "23",
    icon: FileText,
  },
  30024: {
    kind: 30024,
    name: "Draft Article",
    description: "Draft Long-form Content",
    nip: "23",
    icon: FileText,
  },
  30030: {
    kind: 30030,
    name: "Emoji Sets",
    description: "Emoji sets",
    nip: "51",
    icon: Smile,
  },
  30078: {
    kind: 30078,
    name: "App Data",
    description: "Application-specific Data",
    nip: "78",
    icon: Settings,
  },
  30311: {
    kind: 30311,
    name: "Live Event",
    description: "Live Event",
    nip: "53",
    icon: Video,
  },
  30312: {
    kind: 30312,
    name: "Live Chat Msg",
    description: "Live Chat Message (Deprecated)",
    nip: "53",
    icon: MessageCircle,
  },
  30313: {
    kind: 30313,
    name: "Live Status",
    description: "Live Event Status",
    nip: "53",
    icon: Timer,
  },
  30315: {
    kind: 30315,
    name: "Status",
    description: "User Statuses",
    nip: "38",
    icon: MessageSquare,
  },
  30402: {
    kind: 30402,
    name: "Classified",
    description: "Classified Listing",
    nip: "99",
    icon: ShoppingBag,
  },
  30403: {
    kind: 30403,
    name: "Classified Draft",
    description: "Draft Classified Listing",
    nip: "99",
    icon: ShoppingBag,
  },
  30617: {
    kind: 30617,
    name: "Repo Announce",
    description: "Repository announcements",
    nip: "34",
    icon: GitBranch,
  },
  30818: {
    kind: 30818,
    name: "Wiki",
    description: "Wiki article",
    nip: "54",
    icon: FileText,
  },
  30819: {
    kind: 30819,
    name: "Wiki Redirect",
    description: "Redirects to a wiki article",
    nip: "54",
    icon: FileText,
  },
  31922: {
    kind: 31922,
    name: "Calendar Event",
    description: "Date-Based Calendar Event",
    nip: "52",
    icon: Calendar,
  },
  31923: {
    kind: 31923,
    name: "Time Event",
    description: "Time-Based Calendar Event",
    nip: "52",
    icon: Calendar,
  },
  31924: {
    kind: 31924,
    name: "Calendar",
    description: "Calendar",
    nip: "52",
    icon: Calendar,
  },
  31925: {
    kind: 31925,
    name: "Calendar RSVP",
    description: "Calendar Event RSVP",
    nip: "52",
    icon: Calendar,
  },
  31989: {
    kind: 31989,
    name: "Handler Rec",
    description: "Handler recommendation",
    nip: "89",
    icon: Settings,
  },
  34550: {
    kind: 34550,
    name: "Community",
    description: "Community Definition",
    nip: "72",
    icon: Users,
  },
  37516: {
    kind: 37516,
    name: "Geocache",
    description: "Geocache listing",
    nip: "geocaching",
    icon: Map,
  },
  38383: {
    kind: 38383,
    name: "P2P Order",
    description: "Peer-to-peer Order events",
    nip: "69",
    icon: ShoppingBag,
  },
  39701: {
    kind: 39701,
    name: "Web Bookmarks",
    description: "Web bookmarks",
    nip: "B0",
    icon: Bookmark,
  },
};

export function getKindInfo(kind: number): EventKind | undefined {
  return EVENT_KINDS[kind];
}

export function getKindName(kind: number): string {
  return EVENT_KINDS[kind]?.name || `Kind ${kind}`;
}

export function getKindIcon(kind: number): LucideIcon {
  return EVENT_KINDS[kind]?.icon || MessageSquare;
}
